---
title: Elmas Agung
tagline: Elmas Agung Blog
description: Elmas Agung Blog
url: elmas.xyz
baseurl: ''
author:
  name: Elmas Agung
  url: https://twitter.com/elmasagung
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: true
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
markdown: ''
highlighter: ''
